---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
# Get data:
# test

```

__Have to run this at the start of the notebook to reload changes to libraries and reload charts or images that are displayed__

```{python}
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline
```

```{python}
from fastai.vision import *
from fastai.metrics import error_rate
```

---
### Set the Batch Size for the Rest of the Project
---

```{python}
bs = 64
fifty_bs = bs // 2
```

---
### Unzip the data from the file (run once)
---

```{python}
import zipfile
import os

folder = 'lesson-1-xray-data'

fp = os.path.join(folder, 'chest-xray-pneumonia.zip')

with zipfile.ZipFile(fp, 'r') as z:
    z.extractall(folder)
```

```{python}
unzipped_folder = os.path.join(folder, 'chest_xray')
os.listdir(unzipped_folder)
```

---
### Explore different ways to get an ImageDataBunch
---

```{python}
doc(ImageDataBunch)
```

```{python}
doc(get_transforms)
```

#### Here's the docs for the one we want
from_folder[source][test]
from_folder(path:PathOrStr, train:PathOrStr='train', valid:PathOrStr='valid', test:Union[Path, str, NoneType]=None, valid_pct=None, seed:int=None, classes:Collection[T_co]=None, **kwargs:Any) → ImageDataBunch

Create from imagenet style dataset in path with train,valid,test subfolders (or provide valid_pct).

Refer to create_from_ll to see all the **kwargs arguments.

"Imagenet-style" datasets look something like this (note that the test folder is optional):

path\
  train\
    clas1\
    clas2\
    ...
  valid\
    clas1\
    clas2\
    ...
  test\
For example:

data = ImageDataBunch.from_folder(path, ds_tfms=tfms, size=24)
Note that this (and all factory methods in this section) pass any kwargs to DataBunch.create.


__from_folder factory looks pretty good since we have an ImageNet style dataset__

```{python}
help(ImageDataBunch.from_folder)
```

---
### Get ImageDataBunch
---

```{python}
print(os.path.join(unzipped_folder, 'chest_xray'))
```

```{python}
print(imagenet_stats)
```

```{python}
help(ImageDataBunch.normalize)
```

```{python}
# test get_transforms vs not get_transforms (adds variation to the data set)
# find out what normalize does
data = ImageDataBunch.from_folder(
    path=os.path.join(unzipped_folder, 'chest_xray'),
    valid='test',
    size=224,
    bs=bs,
    ds_tfms=get_transforms()
).normalize(imagenet_stats)
```

```{python}
fifty_data = ImageDataBunch.from_folder(
    path=os.path.join(unzipped_folder, 'chest_xray'),
    valid='test',
    size=224,
    bs=bs // 2,
    ds_tfms=get_transforms()
).normalize(imagenet_stats)
```

```{python}
data.show_batch(rows=5, figsize=(12,10))
```

```{python}
print(data.classes)
data.c
```

---
### Make the Model and train it
---

```{python}
learn = cnn_learner(fifty_data, models.resnet50, metrics=error_rate)
```

```{python}
learn.fit_one_cycle(4)
```

```{python}
learn.save('stage-1-50')
```

```{python}
interp = ClassificationInterpretation.from_learner(learn)
```

```{python}
interp.plot_confusion_matrix(figsize=(15,15), dpi=60)
```

```{python}
learn.lr_find()
```

```{python}
learn.recorder.plot()
```

```{python}
learn.unfreeze()
learn.fit_one_cycle(2, max_lr=slice(1e-3,1e-2))
```

```{python}
learn.freeze()
learn.fit_one_cycle(2)
```

```{python}
learn.save('stage-2-50')
```

---
### Test with like 50 epochs and train for an hour...
---

```{python}
learn = cnn_learner(fifty_data, models.resnet50, metrics=error_rate)
```

```{python}
learn.fit_one_cycle(50)
```

```{python}

```
